name: Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  saludo:
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Say Hola Mundo
      run: echo "¡Hola mundo! Se ha realizado un push a la rama main."
